// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kben/signnow-api/client/document"
	"github.com/kben/signnow-api/client/document_group"
	//"github.com/kben/signnow-api/client/embedded_signing"
	"github.com/kben/signnow-api/client/folder"
	"github.com/kben/signnow-api/client/o_auth2"
	"github.com/kben/signnow-api/client/signing_link"
	"github.com/kben/signnow-api/client/smart_fields"
	"github.com/kben/signnow-api/client/template"
	"github.com/kben/signnow-api/client/user"
	"github.com/kben/signnow-api/client/webhooks_2_0"
)

// Default sign now HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api-eval.signnow.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new sign now HTTP client.
func NewHTTPClient(formats strfmt.Registry) *SignNow {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new sign now HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *SignNow {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new sign now client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *SignNow {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(SignNow)
	cli.Transport = transport
	cli.Document = document.New(transport, formats)
	cli.DocumentGroup = document_group.New(transport, formats)
	cli.Folder = folder.New(transport, formats)
	cli.OAuth2 = o_auth2.New(transport, formats)
	cli.SigningLink = signing_link.New(transport, formats)
	cli.SmartFields = smart_fields.New(transport, formats)
	cli.Template = template.New(transport, formats)
	cli.User = user.New(transport, formats)
	cli.Webhooks20 = webhooks_2_0.New(transport, formats)
	//cli.EmbeddedSigning = embedded_signing.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// SignNow is a client for sign now
type SignNow struct {
	Document document.ClientService

	DocumentGroup document_group.ClientService

	Folder folder.ClientService

	OAuth2 o_auth2.ClientService

	SigningLink signing_link.ClientService

	SmartFields smart_fields.ClientService

	Template template.ClientService

	User user.ClientService

	Webhooks20 webhooks_2_0.ClientService

	Transport runtime.ClientTransport

	//EmbeddedSigning embedded_signing.ClientService
}

// SetTransport changes the transport on the client and all its subresources
func (c *SignNow) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Document.SetTransport(transport)
	c.DocumentGroup.SetTransport(transport)
	c.Folder.SetTransport(transport)
	c.OAuth2.SetTransport(transport)
	c.SigningLink.SetTransport(transport)
	c.SmartFields.SetTransport(transport)
	c.Template.SetTransport(transport)
	c.User.SetTransport(transport)
	c.Webhooks20.SetTransport(transport)
	//	c.EmbeddedSigning.SetTransport(transport)
}
