// Code generated by go-swagger; DO NOT EDIT.

package embedded_signing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkReader is a Reader for the PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLink structure.
type PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK creates a PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK with default headers values
func NewPostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK() *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK {
	return &PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK{}
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK handles this case with default header values.

PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK post v2 documents document Id embedded invites field invite unique Id link o k
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK struct {
	Payload *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK) Error() string {
	return fmt.Sprintf("[POST /v2/documents/{document_id}/embedded-invites/{fieldInviteUniqueId}/link][%d] postV2DocumentsDocumentIdEmbeddedInvitesFieldInviteUniqueIdLinkOK  %+v", 200, o.Payload)
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK) GetPayload() *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody {
	return o.Payload
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkBody post v2 documents document ID embedded invites field invite unique ID link body
swagger:model PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkBody
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkBody struct {

	// auth method
	AuthMethod string `json:"auth_method,omitempty"`

	// link expiration
	LinkExpiration int64 `json:"link_expiration,omitempty"`
}

// Validate validates this post v2 documents document ID embedded invites field invite unique ID link body
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkBody) UnmarshalBinary(b []byte) error {
	var res PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody post v2 documents document ID embedded invites field invite unique ID link o k body
swagger:model PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody struct {

	// data
	Data *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBodyData `json:"data,omitempty"`
}

// Validate validates this post v2 documents document ID embedded invites field invite unique ID link o k body
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postV2DocumentsDocumentIdEmbeddedInvitesFieldInviteUniqueIdLinkOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody) UnmarshalBinary(b []byte) error {
	var res PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBodyData post v2 documents document ID embedded invites field invite unique ID link o k body data
swagger:model PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBodyData
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBodyData struct {

	// link
	Link string `json:"link,omitempty"`
}

// Validate validates this post v2 documents document ID embedded invites field invite unique ID link o k body data
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBodyData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBodyData) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBodyData) UnmarshalBinary(b []byte) error {
	var res PostV2DocumentsDocumentIDEmbeddedInvitesFieldInviteUniqueIDLinkOKBodyData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
