// Code generated by go-swagger; DO NOT EDIT.

package embedded_signing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostV2DocumentsDocumentIDEmbeddedInvitesReader is a Reader for the PostV2DocumentsDocumentIDEmbeddedInvites structure.
type PostV2DocumentsDocumentIDEmbeddedInvitesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostV2DocumentsDocumentIDEmbeddedInvitesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostV2DocumentsDocumentIDEmbeddedInvitesCreated creates a PostV2DocumentsDocumentIDEmbeddedInvitesCreated with default headers values
func NewPostV2DocumentsDocumentIDEmbeddedInvitesCreated() *PostV2DocumentsDocumentIDEmbeddedInvitesCreated {
	return &PostV2DocumentsDocumentIDEmbeddedInvitesCreated{}
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesCreated handles this case with default header values.

PostV2DocumentsDocumentIDEmbeddedInvitesCreated post v2 documents document Id embedded invites created
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesCreated struct {
	Payload *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreated) Error() string {
	return fmt.Sprintf("[POST /v2/documents/{document_id}/embedded-invites][%d] postV2DocumentsDocumentIdEmbeddedInvitesCreated  %+v", 201, o.Payload)
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreated) GetPayload() *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody {
	return o.Payload
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesBody post v2 documents document ID embedded invites body
swagger:model PostV2DocumentsDocumentIDEmbeddedInvitesBody
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesBody struct {

	// invites
	// Required: true
	Invites []*PostV2DocumentsDocumentIDEmbeddedInvitesParamsBodyInvitesItems0 `json:"invites"`
}

// Validate validates this post v2 documents document ID embedded invites body
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInvites(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesBody) validateInvites(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"invites", "body", o.Invites); err != nil {
		return err
	}

	for i := 0; i < len(o.Invites); i++ {
		if swag.IsZero(o.Invites[i]) { // not required
			continue
		}

		if o.Invites[i] != nil {
			if err := o.Invites[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "invites" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesBody) UnmarshalBinary(b []byte) error {
	var res PostV2DocumentsDocumentIDEmbeddedInvitesBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody post v2 documents document ID embedded invites created body
swagger:model PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody struct {

	// data
	Data []*PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBodyDataItems0 `json:"data"`
}

// Validate validates this post v2 documents document ID embedded invites created body
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("postV2DocumentsDocumentIdEmbeddedInvitesCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBodyDataItems0 post v2 documents document ID embedded invites created body data items0
swagger:model PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBodyDataItems0
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBodyDataItems0 struct {

	// email
	Email string `json:"email,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// role id
	RoleID string `json:"role_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this post v2 documents document ID embedded invites created body data items0
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBodyDataItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res PostV2DocumentsDocumentIDEmbeddedInvitesCreatedBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostV2DocumentsDocumentIDEmbeddedInvitesParamsBodyInvitesItems0 post v2 documents document ID embedded invites params body invites items0
swagger:model PostV2DocumentsDocumentIDEmbeddedInvitesParamsBodyInvitesItems0
*/
type PostV2DocumentsDocumentIDEmbeddedInvitesParamsBodyInvitesItems0 struct {

	// auth method
	AuthMethod string `json:"auth_method,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// role id
	RoleID string `json:"role_id,omitempty"`
}

// Validate validates this post v2 documents document ID embedded invites params body invites items0
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesParamsBodyInvitesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesParamsBodyInvitesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV2DocumentsDocumentIDEmbeddedInvitesParamsBodyInvitesItems0) UnmarshalBinary(b []byte) error {
	var res PostV2DocumentsDocumentIDEmbeddedInvitesParamsBodyInvitesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
