// Code generated by go-swagger; DO NOT EDIT.

package document_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteDocumentgroupDocumentGroupIDParams creates a new DeleteDocumentgroupDocumentGroupIDParams object
// with the default values initialized.
func NewDeleteDocumentgroupDocumentGroupIDParams() *DeleteDocumentgroupDocumentGroupIDParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &DeleteDocumentgroupDocumentGroupIDParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDocumentgroupDocumentGroupIDParamsWithTimeout creates a new DeleteDocumentgroupDocumentGroupIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDocumentgroupDocumentGroupIDParamsWithTimeout(timeout time.Duration) *DeleteDocumentgroupDocumentGroupIDParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &DeleteDocumentgroupDocumentGroupIDParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewDeleteDocumentgroupDocumentGroupIDParamsWithContext creates a new DeleteDocumentgroupDocumentGroupIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDocumentgroupDocumentGroupIDParamsWithContext(ctx context.Context) *DeleteDocumentgroupDocumentGroupIDParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &DeleteDocumentgroupDocumentGroupIDParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewDeleteDocumentgroupDocumentGroupIDParamsWithHTTPClient creates a new DeleteDocumentgroupDocumentGroupIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDocumentgroupDocumentGroupIDParamsWithHTTPClient(client *http.Client) *DeleteDocumentgroupDocumentGroupIDParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &DeleteDocumentgroupDocumentGroupIDParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*DeleteDocumentgroupDocumentGroupIDParams contains all the parameters to send to the API endpoint
for the delete documentgroup document group ID operation typically these are written to a http.Request
*/
type DeleteDocumentgroupDocumentGroupIDParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*DocumentGroupID*/
	DocumentGroupID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) WithTimeout(timeout time.Duration) *DeleteDocumentgroupDocumentGroupIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) WithContext(ctx context.Context) *DeleteDocumentgroupDocumentGroupIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) WithHTTPClient(client *http.Client) *DeleteDocumentgroupDocumentGroupIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) WithAuthorization(authorization string) *DeleteDocumentgroupDocumentGroupIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithDocumentGroupID adds the documentGroupID to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) WithDocumentGroupID(documentGroupID string) *DeleteDocumentgroupDocumentGroupIDParams {
	o.SetDocumentGroupID(documentGroupID)
	return o
}

// SetDocumentGroupID adds the documentGroupId to the delete documentgroup document group ID params
func (o *DeleteDocumentgroupDocumentGroupIDParams) SetDocumentGroupID(documentGroupID string) {
	o.DocumentGroupID = documentGroupID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDocumentgroupDocumentGroupIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param document_group_id
	if err := r.SetPathParam("document_group_id", o.DocumentGroupID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
