// Code generated by go-swagger; DO NOT EDIT.

package document_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteDocumentgroupDocumentGroupIDReader is a Reader for the DeleteDocumentgroupDocumentGroupID structure.
type DeleteDocumentgroupDocumentGroupIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDocumentgroupDocumentGroupIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDocumentgroupDocumentGroupIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteDocumentgroupDocumentGroupIDOK creates a DeleteDocumentgroupDocumentGroupIDOK with default headers values
func NewDeleteDocumentgroupDocumentGroupIDOK() *DeleteDocumentgroupDocumentGroupIDOK {
	return &DeleteDocumentgroupDocumentGroupIDOK{}
}

/*DeleteDocumentgroupDocumentGroupIDOK handles this case with default header values.

DeleteDocumentgroupDocumentGroupIDOK delete documentgroup document group Id o k
*/
type DeleteDocumentgroupDocumentGroupIDOK struct {
	Payload interface{}
}

func (o *DeleteDocumentgroupDocumentGroupIDOK) Error() string {
	return fmt.Sprintf("[DELETE /documentgroup/{document_group_id}][%d] deleteDocumentgroupDocumentGroupIdOK  %+v", 200, o.Payload)
}

func (o *DeleteDocumentgroupDocumentGroupIDOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteDocumentgroupDocumentGroupIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
