// Code generated by go-swagger; DO NOT EDIT.

package document_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUserDocumentgroupsParams creates a new GetUserDocumentgroupsParams object
// with the default values initialized.
func NewGetUserDocumentgroupsParams() *GetUserDocumentgroupsParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetUserDocumentgroupsParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserDocumentgroupsParamsWithTimeout creates a new GetUserDocumentgroupsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserDocumentgroupsParamsWithTimeout(timeout time.Duration) *GetUserDocumentgroupsParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetUserDocumentgroupsParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewGetUserDocumentgroupsParamsWithContext creates a new GetUserDocumentgroupsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserDocumentgroupsParamsWithContext(ctx context.Context) *GetUserDocumentgroupsParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetUserDocumentgroupsParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewGetUserDocumentgroupsParamsWithHTTPClient creates a new GetUserDocumentgroupsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserDocumentgroupsParamsWithHTTPClient(client *http.Client) *GetUserDocumentgroupsParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetUserDocumentgroupsParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*GetUserDocumentgroupsParams contains all the parameters to send to the API endpoint
for the get user documentgroups operation typically these are written to a http.Request
*/
type GetUserDocumentgroupsParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*Limit*/
	Limit int64
	/*Offset*/
	Offset int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) WithTimeout(timeout time.Duration) *GetUserDocumentgroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) WithContext(ctx context.Context) *GetUserDocumentgroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) WithHTTPClient(client *http.Client) *GetUserDocumentgroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) WithAuthorization(authorization string) *GetUserDocumentgroupsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithLimit adds the limit to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) WithLimit(limit int64) *GetUserDocumentgroupsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) SetLimit(limit int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) WithOffset(offset int64) *GetUserDocumentgroupsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get user documentgroups params
func (o *GetUserDocumentgroupsParams) SetOffset(offset int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserDocumentgroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// query param limit
	qrLimit := o.Limit
	qLimit := swag.FormatInt64(qrLimit)
	if qLimit != "" {
		if err := r.SetQueryParam("limit", qLimit); err != nil {
			return err
		}
	}

	// query param offset
	qrOffset := o.Offset
	qOffset := swag.FormatInt64(qrOffset)
	if qOffset != "" {
		if err := r.SetQueryParam("offset", qOffset); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
