// Code generated by go-swagger; DO NOT EDIT.

package document_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams creates a new GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams object
// with the default values initialized.
func NewGetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams() *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParamsWithTimeout creates a new GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParamsWithTimeout(timeout time.Duration) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewGetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParamsWithContext creates a new GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParamsWithContext(ctx context.Context) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewGetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParamsWithHTTPClient creates a new GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParamsWithHTTPClient(client *http.Client) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams contains all the parameters to send to the API endpoint
for the get documentgroup document group ID groupinvite invite ID pendinginvites operation typically these are written to a http.Request
*/
type GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*DocumentGroupID*/
	DocumentGroupID string
	/*InviteID*/
	InviteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) WithTimeout(timeout time.Duration) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) WithContext(ctx context.Context) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) WithHTTPClient(client *http.Client) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) WithAuthorization(authorization string) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithDocumentGroupID adds the documentGroupID to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) WithDocumentGroupID(documentGroupID string) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	o.SetDocumentGroupID(documentGroupID)
	return o
}

// SetDocumentGroupID adds the documentGroupId to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) SetDocumentGroupID(documentGroupID string) {
	o.DocumentGroupID = documentGroupID
}

// WithInviteID adds the inviteID to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) WithInviteID(inviteID string) *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams {
	o.SetInviteID(inviteID)
	return o
}

// SetInviteID adds the inviteId to the get documentgroup document group ID groupinvite invite ID pendinginvites params
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) SetInviteID(inviteID string) {
	o.InviteID = inviteID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDocumentgroupDocumentGroupIDGroupinviteInviteIDPendinginvitesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param document_group_id
	if err := r.SetPathParam("document_group_id", o.DocumentGroupID); err != nil {
		return err
	}

	// path param invite_id
	if err := r.SetPathParam("invite_id", o.InviteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
