// Code generated by go-swagger; DO NOT EDIT.

package document_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams creates a new PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams object
// with the default values initialized.
func NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams() *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParamsWithTimeout creates a new PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParamsWithTimeout(timeout time.Duration) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParamsWithContext creates a new PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParamsWithContext(ctx context.Context) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParamsWithHTTPClient creates a new PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParamsWithHTTPClient(client *http.Client) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams contains all the parameters to send to the API endpoint
for the post documentgroup document group ID groupinvite invite ID resendinvites operation typically these are written to a http.Request
*/
type PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*Body
	  Email of the user you want to resend email to. If not present, emails will be resent to all pending users.



	*/
	Body PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesBody
	/*DocumentGroupID*/
	DocumentGroupID string
	/*InviteID*/
	InviteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) WithTimeout(timeout time.Duration) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) WithContext(ctx context.Context) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) WithHTTPClient(client *http.Client) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) WithAuthorization(authorization string) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) WithBody(body PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesBody) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) SetBody(body PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesBody) {
	o.Body = body
}

// WithDocumentGroupID adds the documentGroupID to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) WithDocumentGroupID(documentGroupID string) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	o.SetDocumentGroupID(documentGroupID)
	return o
}

// SetDocumentGroupID adds the documentGroupId to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) SetDocumentGroupID(documentGroupID string) {
	o.DocumentGroupID = documentGroupID
}

// WithInviteID adds the inviteID to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) WithInviteID(inviteID string) *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams {
	o.SetInviteID(inviteID)
	return o
}

// SetInviteID adds the inviteId to the post documentgroup document group ID groupinvite invite ID resendinvites params
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) SetInviteID(inviteID string) {
	o.InviteID = inviteID
}

// WriteToRequest writes these params to a swagger request
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDResendinvitesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param document_group_id
	if err := r.SetPathParam("document_group_id", o.DocumentGroupID); err != nil {
		return err
	}

	// path param invite_id
	if err := r.SetPathParam("invite_id", o.InviteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
