// Code generated by go-swagger; DO NOT EDIT.

package document_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteReader is a Reader for the PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinvite structure.
type PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK creates a PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK with default headers values
func NewPostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK() *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK {
	return &PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK{}
}

/*PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK handles this case with default header values.

PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK post documentgroup document group Id groupinvite invite Id cancelinvite o k
*/
type PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK struct {
	Payload interface{}
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK) Error() string {
	return fmt.Sprintf("[POST /documentgroup/{document_group_id}/groupinvite/{invite_id}/cancelinvite][%d] postDocumentgroupDocumentGroupIdGroupinviteInviteIdCancelinviteOK  %+v", 200, o.Payload)
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteInviteIDCancelinviteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
