// Code generated by go-swagger; DO NOT EDIT.

package document_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDocumentgroupDocumentGroupIDGroupinviteReader is a Reader for the PostDocumentgroupDocumentGroupIDGroupinvite structure.
type PostDocumentgroupDocumentGroupIDGroupinviteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDocumentgroupDocumentGroupIDGroupinviteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDocumentgroupDocumentGroupIDGroupinviteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDocumentgroupDocumentGroupIDGroupinviteOK creates a PostDocumentgroupDocumentGroupIDGroupinviteOK with default headers values
func NewPostDocumentgroupDocumentGroupIDGroupinviteOK() *PostDocumentgroupDocumentGroupIDGroupinviteOK {
	return &PostDocumentgroupDocumentGroupIDGroupinviteOK{}
}

/*PostDocumentgroupDocumentGroupIDGroupinviteOK handles this case with default header values.

PostDocumentgroupDocumentGroupIDGroupinviteOK post documentgroup document group Id groupinvite o k
*/
type PostDocumentgroupDocumentGroupIDGroupinviteOK struct {
	Payload interface{}
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteOK) Error() string {
	return fmt.Sprintf("[POST /documentgroup/{document_group_id}/groupinvite][%d] postDocumentgroupDocumentGroupIdGroupinviteOK  %+v", 200, o.Payload)
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostDocumentgroupDocumentGroupIDGroupinviteBody post documentgroup document group ID groupinvite body
swagger:model PostDocumentgroupDocumentGroupIDGroupinviteBody
*/
type PostDocumentgroupDocumentGroupIDGroupinviteBody struct {

	// completion emails
	CompletionEmails []*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0 `json:"completion_emails"`

	// invite steps
	InviteSteps []*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0 `json:"invite_steps"`
}

// Validate validates this post documentgroup document group ID groupinvite body
func (o *PostDocumentgroupDocumentGroupIDGroupinviteBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCompletionEmails(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateInviteSteps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteBody) validateCompletionEmails(formats strfmt.Registry) error {

	if swag.IsZero(o.CompletionEmails) { // not required
		return nil
	}

	for i := 0; i < len(o.CompletionEmails); i++ {
		if swag.IsZero(o.CompletionEmails[i]) { // not required
			continue
		}

		if o.CompletionEmails[i] != nil {
			if err := o.CompletionEmails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "completion_emails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteBody) validateInviteSteps(formats strfmt.Registry) error {

	if swag.IsZero(o.InviteSteps) { // not required
		return nil
	}

	for i := 0; i < len(o.InviteSteps); i++ {
		if swag.IsZero(o.InviteSteps[i]) { // not required
			continue
		}

		if o.InviteSteps[i] != nil {
			if err := o.InviteSteps[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "invite_steps" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteBody) UnmarshalBinary(b []byte) error {
	var res PostDocumentgroupDocumentGroupIDGroupinviteBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0 post documentgroup document group ID groupinvite params body completion emails items0
swagger:model PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0
*/
type PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0 struct {

	// disabled
	Disabled int64 `json:"disabled,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this post documentgroup document group ID groupinvite params body completion emails items0
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(o.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0) UnmarshalBinary(b []byte) error {
	var res PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyCompletionEmailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0 post documentgroup document group ID groupinvite params body invite steps items0
swagger:model PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0
*/
type PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0 struct {

	// invite actions
	InviteActions []*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0 `json:"invite_actions"`

	// invite emails
	InviteEmails []*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0 `json:"invite_emails"`

	// order
	Order int64 `json:"order,omitempty"`
}

// Validate validates this post documentgroup document group ID groupinvite params body invite steps items0
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInviteActions(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateInviteEmails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0) validateInviteActions(formats strfmt.Registry) error {

	if swag.IsZero(o.InviteActions) { // not required
		return nil
	}

	for i := 0; i < len(o.InviteActions); i++ {
		if swag.IsZero(o.InviteActions[i]) { // not required
			continue
		}

		if o.InviteActions[i] != nil {
			if err := o.InviteActions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("invite_actions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0) validateInviteEmails(formats strfmt.Registry) error {

	if swag.IsZero(o.InviteEmails) { // not required
		return nil
	}

	for i := 0; i < len(o.InviteEmails); i++ {
		if swag.IsZero(o.InviteEmails[i]) { // not required
			continue
		}

		if o.InviteEmails[i] != nil {
			if err := o.InviteEmails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("invite_emails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0) UnmarshalBinary(b []byte) error {
	var res PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0 post documentgroup document group ID groupinvite params body invite steps items0 invite actions items0
swagger:model PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0
*/
type PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0 struct {

	// action
	Action string `json:"action,omitempty"`

	// allow reassign
	AllowReassign int64 `json:"allow_reassign,omitempty"`

	// authentication
	Authentication *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0Authentication `json:"authentication,omitempty"`

	// document id
	DocumentID string `json:"document_id,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// role name
	RoleName string `json:"role_name,omitempty"`
}

// Validate validates this post documentgroup document group ID groupinvite params body invite steps items0 invite actions items0
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAuthentication(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0) validateAuthentication(formats strfmt.Registry) error {

	if swag.IsZero(o.Authentication) { // not required
		return nil
	}

	if o.Authentication != nil {
		if err := o.Authentication.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("authentication")
			}
			return err
		}
	}

	return nil
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(o.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0) UnmarshalBinary(b []byte) error {
	var res PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0Authentication post documentgroup document group ID groupinvite params body invite steps items0 invite actions items0 authentication
swagger:model PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0Authentication
*/
type PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0Authentication struct {

	// type
	Type string `json:"type,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this post documentgroup document group ID groupinvite params body invite steps items0 invite actions items0 authentication
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0Authentication) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0Authentication) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0Authentication) UnmarshalBinary(b []byte) error {
	var res PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteActionsItems0Authentication
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0 post documentgroup document group ID groupinvite params body invite steps items0 invite emails items0
swagger:model PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0
*/
type PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0 struct {

	// disabled
	Disabled int64 `json:"disabled,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this post documentgroup document group ID groupinvite params body invite steps items0 invite emails items0
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(o.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0) UnmarshalBinary(b []byte) error {
	var res PostDocumentgroupDocumentGroupIDGroupinviteParamsBodyInviteStepsItems0InviteEmailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
