// Code generated by go-swagger; DO NOT EDIT.

package webhooks_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIV2EventsEventSubscriptionIDReader is a Reader for the DeleteAPIV2EventsEventSubscriptionID structure.
type DeleteAPIV2EventsEventSubscriptionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV2EventsEventSubscriptionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIV2EventsEventSubscriptionIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteAPIV2EventsEventSubscriptionIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIV2EventsEventSubscriptionIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIV2EventsEventSubscriptionIDNoContent creates a DeleteAPIV2EventsEventSubscriptionIDNoContent with default headers values
func NewDeleteAPIV2EventsEventSubscriptionIDNoContent() *DeleteAPIV2EventsEventSubscriptionIDNoContent {
	return &DeleteAPIV2EventsEventSubscriptionIDNoContent{}
}

/*DeleteAPIV2EventsEventSubscriptionIDNoContent handles this case with default header values.

DeleteAPIV2EventsEventSubscriptionIDNoContent delete Api v2 events event subscription Id no content
*/
type DeleteAPIV2EventsEventSubscriptionIDNoContent struct {
	Payload interface{}
}

func (o *DeleteAPIV2EventsEventSubscriptionIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/events/{event_subscription_id}][%d] deleteApiV2EventsEventSubscriptionIdNoContent  %+v", 204, o.Payload)
}

func (o *DeleteAPIV2EventsEventSubscriptionIDNoContent) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteAPIV2EventsEventSubscriptionIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIV2EventsEventSubscriptionIDForbidden creates a DeleteAPIV2EventsEventSubscriptionIDForbidden with default headers values
func NewDeleteAPIV2EventsEventSubscriptionIDForbidden() *DeleteAPIV2EventsEventSubscriptionIDForbidden {
	return &DeleteAPIV2EventsEventSubscriptionIDForbidden{}
}

/*DeleteAPIV2EventsEventSubscriptionIDForbidden handles this case with default header values.

**For basic auth:**

Application id which is used for request differs from application id created given event subscription.

**For bearer auth:**

The event subscription was created by another user
*/
type DeleteAPIV2EventsEventSubscriptionIDForbidden struct {
}

func (o *DeleteAPIV2EventsEventSubscriptionIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/events/{event_subscription_id}][%d] deleteApiV2EventsEventSubscriptionIdForbidden ", 403)
}

func (o *DeleteAPIV2EventsEventSubscriptionIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV2EventsEventSubscriptionIDNotFound creates a DeleteAPIV2EventsEventSubscriptionIDNotFound with default headers values
func NewDeleteAPIV2EventsEventSubscriptionIDNotFound() *DeleteAPIV2EventsEventSubscriptionIDNotFound {
	return &DeleteAPIV2EventsEventSubscriptionIDNotFound{}
}

/*DeleteAPIV2EventsEventSubscriptionIDNotFound handles this case with default header values.

Value of "uniqueEventId" doesn't exist in database
*/
type DeleteAPIV2EventsEventSubscriptionIDNotFound struct {
}

func (o *DeleteAPIV2EventsEventSubscriptionIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/events/{event_subscription_id}][%d] deleteApiV2EventsEventSubscriptionIdNotFound ", 404)
}

func (o *DeleteAPIV2EventsEventSubscriptionIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
