// Code generated by go-swagger; DO NOT EDIT.

package webhooks_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV2EventsParams creates a new PostAPIV2EventsParams object
// with the default values initialized.
func NewPostAPIV2EventsParams() *PostAPIV2EventsParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostAPIV2EventsParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV2EventsParamsWithTimeout creates a new PostAPIV2EventsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV2EventsParamsWithTimeout(timeout time.Duration) *PostAPIV2EventsParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostAPIV2EventsParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPostAPIV2EventsParamsWithContext creates a new PostAPIV2EventsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV2EventsParamsWithContext(ctx context.Context) *PostAPIV2EventsParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostAPIV2EventsParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPostAPIV2EventsParamsWithHTTPClient creates a new PostAPIV2EventsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV2EventsParamsWithHTTPClient(client *http.Client) *PostAPIV2EventsParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostAPIV2EventsParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*PostAPIV2EventsParams contains all the parameters to send to the API endpoint
for the post API v2 events operation typically these are written to a http.Request
*/
type PostAPIV2EventsParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*Body*/
	Body PostAPIV2EventsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v2 events params
func (o *PostAPIV2EventsParams) WithTimeout(timeout time.Duration) *PostAPIV2EventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v2 events params
func (o *PostAPIV2EventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v2 events params
func (o *PostAPIV2EventsParams) WithContext(ctx context.Context) *PostAPIV2EventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v2 events params
func (o *PostAPIV2EventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v2 events params
func (o *PostAPIV2EventsParams) WithHTTPClient(client *http.Client) *PostAPIV2EventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v2 events params
func (o *PostAPIV2EventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API v2 events params
func (o *PostAPIV2EventsParams) WithAuthorization(authorization string) *PostAPIV2EventsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API v2 events params
func (o *PostAPIV2EventsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the post API v2 events params
func (o *PostAPIV2EventsParams) WithBody(body PostAPIV2EventsBody) *PostAPIV2EventsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v2 events params
func (o *PostAPIV2EventsParams) SetBody(body PostAPIV2EventsBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV2EventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
