// Code generated by go-swagger; DO NOT EDIT.

package webhooks_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutAPIV2EventsEventSubscriptionIDReader is a Reader for the PutAPIV2EventsEventSubscriptionID structure.
type PutAPIV2EventsEventSubscriptionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV2EventsEventSubscriptionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPutAPIV2EventsEventSubscriptionIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV2EventsEventSubscriptionIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIV2EventsEventSubscriptionIDCreated creates a PutAPIV2EventsEventSubscriptionIDCreated with default headers values
func NewPutAPIV2EventsEventSubscriptionIDCreated() *PutAPIV2EventsEventSubscriptionIDCreated {
	return &PutAPIV2EventsEventSubscriptionIDCreated{}
}

/*PutAPIV2EventsEventSubscriptionIDCreated handles this case with default header values.

PutAPIV2EventsEventSubscriptionIDCreated put Api v2 events event subscription Id created
*/
type PutAPIV2EventsEventSubscriptionIDCreated struct {
	Payload *PutAPIV2EventsEventSubscriptionIDCreatedBody
}

func (o *PutAPIV2EventsEventSubscriptionIDCreated) Error() string {
	return fmt.Sprintf("[PUT /api/v2/events/{event_subscription_id}][%d] putApiV2EventsEventSubscriptionIdCreated  %+v", 201, o.Payload)
}

func (o *PutAPIV2EventsEventSubscriptionIDCreated) GetPayload() *PutAPIV2EventsEventSubscriptionIDCreatedBody {
	return o.Payload
}

func (o *PutAPIV2EventsEventSubscriptionIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PutAPIV2EventsEventSubscriptionIDCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIV2EventsEventSubscriptionIDBadRequest creates a PutAPIV2EventsEventSubscriptionIDBadRequest with default headers values
func NewPutAPIV2EventsEventSubscriptionIDBadRequest() *PutAPIV2EventsEventSubscriptionIDBadRequest {
	return &PutAPIV2EventsEventSubscriptionIDBadRequest{}
}

/*PutAPIV2EventsEventSubscriptionIDBadRequest handles this case with default header values.

* "attributes must not be empty" - "attributes" array is missing or empty
* "'callback' is missing." -  required parameter "callback" is missing
* "Action must be equal 'callback'" - required parameter "action" is missing OR value of "action" parameter differs from 'callback'
* "event must not be empty" - required parameter "event" is missing or has an empty value
* "event must be string" - value of the "event" parameter is not a string
* "callback must be string" - value of the "callback" parameter is not a string
* "callback must be url" - value of "callback" parameter is not an URL
* "Invalid integration id - {integration_id}" - value of "integration_id" parameter doesn't exist in database
 */
type PutAPIV2EventsEventSubscriptionIDBadRequest struct {
}

func (o *PutAPIV2EventsEventSubscriptionIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v2/events/{event_subscription_id}][%d] putApiV2EventsEventSubscriptionIdBadRequest ", 400)
}

func (o *PutAPIV2EventsEventSubscriptionIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PutAPIV2EventsEventSubscriptionIDBody put API v2 events event subscription ID body
swagger:model PutAPIV2EventsEventSubscriptionIDBody
*/
type PutAPIV2EventsEventSubscriptionIDBody struct {

	// action
	Action string `json:"action,omitempty"`

	// attributes
	Attributes *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes `json:"attributes,omitempty"`

	// entity id
	EntityID string `json:"entity_id,omitempty"`

	// event
	Event string `json:"event,omitempty"`
}

// Validate validates this put API v2 events event subscription ID body
func (o *PutAPIV2EventsEventSubscriptionIDBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAttributes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutAPIV2EventsEventSubscriptionIDBody) validateAttributes(formats strfmt.Registry) error {

	if swag.IsZero(o.Attributes) { // not required
		return nil
	}

	if o.Attributes != nil {
		if err := o.Attributes.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "attributes")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutAPIV2EventsEventSubscriptionIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutAPIV2EventsEventSubscriptionIDBody) UnmarshalBinary(b []byte) error {
	var res PutAPIV2EventsEventSubscriptionIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PutAPIV2EventsEventSubscriptionIDCreatedBody put API v2 events event subscription ID created body
swagger:model PutAPIV2EventsEventSubscriptionIDCreatedBody
*/
type PutAPIV2EventsEventSubscriptionIDCreatedBody struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this put API v2 events event subscription ID created body
func (o *PutAPIV2EventsEventSubscriptionIDCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutAPIV2EventsEventSubscriptionIDCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutAPIV2EventsEventSubscriptionIDCreatedBody) UnmarshalBinary(b []byte) error {
	var res PutAPIV2EventsEventSubscriptionIDCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes put API v2 events event subscription ID params body attributes
swagger:model PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes
*/
type PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes struct {

	// callback
	Callback string `json:"callback,omitempty"`

	// docid queryparam
	DocidQueryparam bool `json:"docid_queryparam,omitempty"`

	// headers
	Headers *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributesHeaders `json:"headers,omitempty"`

	// integration id
	IntegrationID string `json:"integration_id,omitempty"`

	// use tls 12
	UseTLS12 bool `json:"use_tls_12,omitempty"`
}

// Validate validates this put API v2 events event subscription ID params body attributes
func (o *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateHeaders(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes) validateHeaders(formats strfmt.Registry) error {

	if swag.IsZero(o.Headers) { // not required
		return nil
	}

	if o.Headers != nil {
		if err := o.Headers.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "attributes" + "." + "headers")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes) UnmarshalBinary(b []byte) error {
	var res PutAPIV2EventsEventSubscriptionIDParamsBodyAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PutAPIV2EventsEventSubscriptionIDParamsBodyAttributesHeaders put API v2 events event subscription ID params body attributes headers
swagger:model PutAPIV2EventsEventSubscriptionIDParamsBodyAttributesHeaders
*/
type PutAPIV2EventsEventSubscriptionIDParamsBodyAttributesHeaders struct {

	// bool head
	BoolHead bool `json:"bool_head,omitempty"`

	// float head
	FloatHead float64 `json:"float_head,omitempty"`

	// int head
	IntHead int64 `json:"int_head,omitempty"`

	// string head
	StringHead string `json:"string_head,omitempty"`
}

// Validate validates this put API v2 events event subscription ID params body attributes headers
func (o *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributesHeaders) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributesHeaders) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutAPIV2EventsEventSubscriptionIDParamsBodyAttributesHeaders) UnmarshalBinary(b []byte) error {
	var res PutAPIV2EventsEventSubscriptionIDParamsBodyAttributesHeaders
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
