// Code generated by go-swagger; DO NOT EDIT.

package webhooks_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIV2EventsEventSubscriptionIDParams creates a new PutAPIV2EventsEventSubscriptionIDParams object
// with the default values initialized.
func NewPutAPIV2EventsEventSubscriptionIDParams() *PutAPIV2EventsEventSubscriptionIDParams {
	var ()
	return &PutAPIV2EventsEventSubscriptionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV2EventsEventSubscriptionIDParamsWithTimeout creates a new PutAPIV2EventsEventSubscriptionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV2EventsEventSubscriptionIDParamsWithTimeout(timeout time.Duration) *PutAPIV2EventsEventSubscriptionIDParams {
	var ()
	return &PutAPIV2EventsEventSubscriptionIDParams{

		timeout: timeout,
	}
}

// NewPutAPIV2EventsEventSubscriptionIDParamsWithContext creates a new PutAPIV2EventsEventSubscriptionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV2EventsEventSubscriptionIDParamsWithContext(ctx context.Context) *PutAPIV2EventsEventSubscriptionIDParams {
	var ()
	return &PutAPIV2EventsEventSubscriptionIDParams{

		Context: ctx,
	}
}

// NewPutAPIV2EventsEventSubscriptionIDParamsWithHTTPClient creates a new PutAPIV2EventsEventSubscriptionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV2EventsEventSubscriptionIDParamsWithHTTPClient(client *http.Client) *PutAPIV2EventsEventSubscriptionIDParams {
	var ()
	return &PutAPIV2EventsEventSubscriptionIDParams{
		HTTPClient: client,
	}
}

/*PutAPIV2EventsEventSubscriptionIDParams contains all the parameters to send to the API endpoint
for the put API v2 events event subscription ID operation typically these are written to a http.Request
*/
type PutAPIV2EventsEventSubscriptionIDParams struct {

	/*Authorization
	  This endpoint accepts either 'Bearer' or 'Basic' token

	*/
	Authorization *string
	/*Body*/
	Body PutAPIV2EventsEventSubscriptionIDBody
	/*EventSubscriptionID*/
	EventSubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) WithTimeout(timeout time.Duration) *PutAPIV2EventsEventSubscriptionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) WithContext(ctx context.Context) *PutAPIV2EventsEventSubscriptionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) WithHTTPClient(client *http.Client) *PutAPIV2EventsEventSubscriptionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) WithAuthorization(authorization *string) *PutAPIV2EventsEventSubscriptionIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithBody adds the body to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) WithBody(body PutAPIV2EventsEventSubscriptionIDBody) *PutAPIV2EventsEventSubscriptionIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) SetBody(body PutAPIV2EventsEventSubscriptionIDBody) {
	o.Body = body
}

// WithEventSubscriptionID adds the eventSubscriptionID to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) WithEventSubscriptionID(eventSubscriptionID string) *PutAPIV2EventsEventSubscriptionIDParams {
	o.SetEventSubscriptionID(eventSubscriptionID)
	return o
}

// SetEventSubscriptionID adds the eventSubscriptionId to the put API v2 events event subscription ID params
func (o *PutAPIV2EventsEventSubscriptionIDParams) SetEventSubscriptionID(eventSubscriptionID string) {
	o.EventSubscriptionID = eventSubscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV2EventsEventSubscriptionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param event_subscription_id
	if err := r.SetPathParam("event_subscription_id", o.EventSubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
