// Code generated by go-swagger; DO NOT EDIT.

package folder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetFolderFolderIDReader is a Reader for the GetFolderFolderID structure.
type GetFolderFolderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFolderFolderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFolderFolderIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFolderFolderIDOK creates a GetFolderFolderIDOK with default headers values
func NewGetFolderFolderIDOK() *GetFolderFolderIDOK {
	return &GetFolderFolderIDOK{}
}

/*GetFolderFolderIDOK handles this case with default header values.

GetFolderFolderIDOK get folder folder Id o k
*/
type GetFolderFolderIDOK struct {
	Payload interface{}
}

func (o *GetFolderFolderIDOK) Error() string {
	return fmt.Sprintf("[GET /folder/{folder_id}][%d] getFolderFolderIdOK  %+v", 200, o.Payload)
}

func (o *GetFolderFolderIDOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetFolderFolderIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
