// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDocumentFieldextractParams creates a new PostDocumentFieldextractParams object
// with the default values initialized.
func NewPostDocumentFieldextractParams() *PostDocumentFieldextractParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentFieldextractParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDocumentFieldextractParamsWithTimeout creates a new PostDocumentFieldextractParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDocumentFieldextractParamsWithTimeout(timeout time.Duration) *PostDocumentFieldextractParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentFieldextractParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPostDocumentFieldextractParamsWithContext creates a new PostDocumentFieldextractParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDocumentFieldextractParamsWithContext(ctx context.Context) *PostDocumentFieldextractParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentFieldextractParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPostDocumentFieldextractParamsWithHTTPClient creates a new PostDocumentFieldextractParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDocumentFieldextractParamsWithHTTPClient(client *http.Client) *PostDocumentFieldextractParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentFieldextractParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*PostDocumentFieldextractParams contains all the parameters to send to the API endpoint
for the post document fieldextract operation typically these are written to a http.Request
*/
type PostDocumentFieldextractParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*File
	  Path to the file

	*/
	File *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post document fieldextract params
func (o *PostDocumentFieldextractParams) WithTimeout(timeout time.Duration) *PostDocumentFieldextractParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post document fieldextract params
func (o *PostDocumentFieldextractParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post document fieldextract params
func (o *PostDocumentFieldextractParams) WithContext(ctx context.Context) *PostDocumentFieldextractParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post document fieldextract params
func (o *PostDocumentFieldextractParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post document fieldextract params
func (o *PostDocumentFieldextractParams) WithHTTPClient(client *http.Client) *PostDocumentFieldextractParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post document fieldextract params
func (o *PostDocumentFieldextractParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post document fieldextract params
func (o *PostDocumentFieldextractParams) WithAuthorization(authorization string) *PostDocumentFieldextractParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post document fieldextract params
func (o *PostDocumentFieldextractParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithFile adds the file to the post document fieldextract params
func (o *PostDocumentFieldextractParams) WithFile(file *string) *PostDocumentFieldextractParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the post document fieldextract params
func (o *PostDocumentFieldextractParams) SetFile(file *string) {
	o.File = file
}

// WriteToRequest writes these params to a swagger request
func (o *PostDocumentFieldextractParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.File != nil {

		// form param file
		var frFile string
		if o.File != nil {
			frFile = *o.File
		}
		fFile := frFile
		if fFile != "" {
			if err := r.SetFormParam("file", fFile); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
