// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostDocumentFieldextractReader is a Reader for the PostDocumentFieldextract structure.
type PostDocumentFieldextractReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDocumentFieldextractReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDocumentFieldextractOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDocumentFieldextractOK creates a PostDocumentFieldextractOK with default headers values
func NewPostDocumentFieldextractOK() *PostDocumentFieldextractOK {
	return &PostDocumentFieldextractOK{}
}

/*PostDocumentFieldextractOK handles this case with default header values.

PostDocumentFieldextractOK post document fieldextract o k
*/
type PostDocumentFieldextractOK struct {
	Payload *PostDocumentFieldextractOKBody
}

func (o *PostDocumentFieldextractOK) Error() string {
	return fmt.Sprintf("[POST /document/fieldextract][%d] postDocumentFieldextractOK  %+v", 200, o.Payload)
}

func (o *PostDocumentFieldextractOK) GetPayload() *PostDocumentFieldextractOKBody {
	return o.Payload
}

func (o *PostDocumentFieldextractOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostDocumentFieldextractOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostDocumentFieldextractOKBody post document fieldextract o k body
swagger:model PostDocumentFieldextractOKBody
*/
type PostDocumentFieldextractOKBody struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this post document fieldextract o k body
func (o *PostDocumentFieldextractOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostDocumentFieldextractOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDocumentFieldextractOKBody) UnmarshalBinary(b []byte) error {
	var res PostDocumentFieldextractOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
