// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDocumentDocumentIDMoveParams creates a new PostDocumentDocumentIDMoveParams object
// with the default values initialized.
func NewPostDocumentDocumentIDMoveParams() *PostDocumentDocumentIDMoveParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentDocumentIDMoveParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDocumentDocumentIDMoveParamsWithTimeout creates a new PostDocumentDocumentIDMoveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDocumentDocumentIDMoveParamsWithTimeout(timeout time.Duration) *PostDocumentDocumentIDMoveParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentDocumentIDMoveParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPostDocumentDocumentIDMoveParamsWithContext creates a new PostDocumentDocumentIDMoveParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDocumentDocumentIDMoveParamsWithContext(ctx context.Context) *PostDocumentDocumentIDMoveParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentDocumentIDMoveParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPostDocumentDocumentIDMoveParamsWithHTTPClient creates a new PostDocumentDocumentIDMoveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDocumentDocumentIDMoveParamsWithHTTPClient(client *http.Client) *PostDocumentDocumentIDMoveParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentDocumentIDMoveParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*PostDocumentDocumentIDMoveParams contains all the parameters to send to the API endpoint
for the post document document ID move operation typically these are written to a http.Request
*/
type PostDocumentDocumentIDMoveParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*Body*/
	Body PostDocumentDocumentIDMoveBody
	/*DocumentID*/
	DocumentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) WithTimeout(timeout time.Duration) *PostDocumentDocumentIDMoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) WithContext(ctx context.Context) *PostDocumentDocumentIDMoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) WithHTTPClient(client *http.Client) *PostDocumentDocumentIDMoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) WithAuthorization(authorization string) *PostDocumentDocumentIDMoveParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) WithBody(body PostDocumentDocumentIDMoveBody) *PostDocumentDocumentIDMoveParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) SetBody(body PostDocumentDocumentIDMoveBody) {
	o.Body = body
}

// WithDocumentID adds the documentID to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) WithDocumentID(documentID string) *PostDocumentDocumentIDMoveParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the post document document ID move params
func (o *PostDocumentDocumentIDMoveParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WriteToRequest writes these params to a swagger request
func (o *PostDocumentDocumentIDMoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param document_id
	if err := r.SetPathParam("document_id", o.DocumentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
