// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDocumentDocumentIDDownloadLinkParams creates a new PostDocumentDocumentIDDownloadLinkParams object
// with the default values initialized.
func NewPostDocumentDocumentIDDownloadLinkParams() *PostDocumentDocumentIDDownloadLinkParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentDocumentIDDownloadLinkParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDocumentDocumentIDDownloadLinkParamsWithTimeout creates a new PostDocumentDocumentIDDownloadLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDocumentDocumentIDDownloadLinkParamsWithTimeout(timeout time.Duration) *PostDocumentDocumentIDDownloadLinkParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentDocumentIDDownloadLinkParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPostDocumentDocumentIDDownloadLinkParamsWithContext creates a new PostDocumentDocumentIDDownloadLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDocumentDocumentIDDownloadLinkParamsWithContext(ctx context.Context) *PostDocumentDocumentIDDownloadLinkParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentDocumentIDDownloadLinkParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPostDocumentDocumentIDDownloadLinkParamsWithHTTPClient creates a new PostDocumentDocumentIDDownloadLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDocumentDocumentIDDownloadLinkParamsWithHTTPClient(client *http.Client) *PostDocumentDocumentIDDownloadLinkParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentDocumentIDDownloadLinkParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*PostDocumentDocumentIDDownloadLinkParams contains all the parameters to send to the API endpoint
for the post document document ID download link operation typically these are written to a http.Request
*/
type PostDocumentDocumentIDDownloadLinkParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*DocumentID*/
	DocumentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) WithTimeout(timeout time.Duration) *PostDocumentDocumentIDDownloadLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) WithContext(ctx context.Context) *PostDocumentDocumentIDDownloadLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) WithHTTPClient(client *http.Client) *PostDocumentDocumentIDDownloadLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) WithAuthorization(authorization string) *PostDocumentDocumentIDDownloadLinkParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithDocumentID adds the documentID to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) WithDocumentID(documentID string) *PostDocumentDocumentIDDownloadLinkParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the post document document ID download link params
func (o *PostDocumentDocumentIDDownloadLinkParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WriteToRequest writes these params to a swagger request
func (o *PostDocumentDocumentIDDownloadLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param document_id
	if err := r.SetPathParam("document_id", o.DocumentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
