// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDocumentMergeParams creates a new PostDocumentMergeParams object
// with the default values initialized.
func NewPostDocumentMergeParams() *PostDocumentMergeParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentMergeParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDocumentMergeParamsWithTimeout creates a new PostDocumentMergeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDocumentMergeParamsWithTimeout(timeout time.Duration) *PostDocumentMergeParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentMergeParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPostDocumentMergeParamsWithContext creates a new PostDocumentMergeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDocumentMergeParamsWithContext(ctx context.Context) *PostDocumentMergeParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentMergeParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPostDocumentMergeParamsWithHTTPClient creates a new PostDocumentMergeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDocumentMergeParamsWithHTTPClient(client *http.Client) *PostDocumentMergeParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentMergeParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*PostDocumentMergeParams contains all the parameters to send to the API endpoint
for the post document merge operation typically these are written to a http.Request
*/
type PostDocumentMergeParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*Body*/
	Body PostDocumentMergeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post document merge params
func (o *PostDocumentMergeParams) WithTimeout(timeout time.Duration) *PostDocumentMergeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post document merge params
func (o *PostDocumentMergeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post document merge params
func (o *PostDocumentMergeParams) WithContext(ctx context.Context) *PostDocumentMergeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post document merge params
func (o *PostDocumentMergeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post document merge params
func (o *PostDocumentMergeParams) WithHTTPClient(client *http.Client) *PostDocumentMergeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post document merge params
func (o *PostDocumentMergeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post document merge params
func (o *PostDocumentMergeParams) WithAuthorization(authorization string) *PostDocumentMergeParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post document merge params
func (o *PostDocumentMergeParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the post document merge params
func (o *PostDocumentMergeParams) WithBody(body PostDocumentMergeBody) *PostDocumentMergeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post document merge params
func (o *PostDocumentMergeParams) SetBody(body PostDocumentMergeBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostDocumentMergeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
