// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostDocumentDocumentIDMoveReader is a Reader for the PostDocumentDocumentIDMove structure.
type PostDocumentDocumentIDMoveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDocumentDocumentIDMoveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDocumentDocumentIDMoveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDocumentDocumentIDMoveOK creates a PostDocumentDocumentIDMoveOK with default headers values
func NewPostDocumentDocumentIDMoveOK() *PostDocumentDocumentIDMoveOK {
	return &PostDocumentDocumentIDMoveOK{}
}

/*PostDocumentDocumentIDMoveOK handles this case with default header values.

PostDocumentDocumentIDMoveOK post document document Id move o k
*/
type PostDocumentDocumentIDMoveOK struct {
	Payload interface{}
}

func (o *PostDocumentDocumentIDMoveOK) Error() string {
	return fmt.Sprintf("[POST /document/{document_id}/move][%d] postDocumentDocumentIdMoveOK  %+v", 200, o.Payload)
}

func (o *PostDocumentDocumentIDMoveOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDocumentDocumentIDMoveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostDocumentDocumentIDMoveBody post document document ID move body
swagger:model PostDocumentDocumentIDMoveBody
*/
type PostDocumentDocumentIDMoveBody struct {

	// folder id
	FolderID string `json:"folder_id,omitempty"`
}

// Validate validates this post document document ID move body
func (o *PostDocumentDocumentIDMoveBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostDocumentDocumentIDMoveBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDocumentDocumentIDMoveBody) UnmarshalBinary(b []byte) error {
	var res PostDocumentDocumentIDMoveBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
