// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDocumentParams creates a new PostDocumentParams object
// with the default values initialized.
func NewPostDocumentParams() *PostDocumentParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDocumentParamsWithTimeout creates a new PostDocumentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDocumentParamsWithTimeout(timeout time.Duration) *PostDocumentParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPostDocumentParamsWithContext creates a new PostDocumentParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDocumentParamsWithContext(ctx context.Context) *PostDocumentParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPostDocumentParamsWithHTTPClient creates a new PostDocumentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDocumentParamsWithHTTPClient(client *http.Client) *PostDocumentParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PostDocumentParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*PostDocumentParams contains all the parameters to send to the API endpoint
for the post document operation typically these are written to a http.Request
*/
type PostDocumentParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*File
	  @/path/to/your/file.pdf

	*/
	File runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post document params
func (o *PostDocumentParams) WithTimeout(timeout time.Duration) *PostDocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post document params
func (o *PostDocumentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post document params
func (o *PostDocumentParams) WithContext(ctx context.Context) *PostDocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post document params
func (o *PostDocumentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post document params
func (o *PostDocumentParams) WithHTTPClient(client *http.Client) *PostDocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post document params
func (o *PostDocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post document params
func (o *PostDocumentParams) WithAuthorization(authorization string) *PostDocumentParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post document params
func (o *PostDocumentParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithFile adds the file to the post document params
func (o *PostDocumentParams) WithFile(name string, file io.Reader) *PostDocumentParams {
	o.SetFile(name, file)
	return o
}

// SetFile adds the file to the post document params
func (o *PostDocumentParams) SetFile(name string, file io.Reader) {
	o.File = runtime.NamedReader(name, file)
}

// WriteToRequest writes these params to a swagger request
func (o *PostDocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// form param file
	frFile := o.File
	if err := r.SetFileParam("file", frFile); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
