// Code generated by go-swagger; DO NOT EDIT.

package document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutDocumentDocumentIDFieldinvitecancelParams creates a new PutDocumentDocumentIDFieldinvitecancelParams object
// with the default values initialized.
func NewPutDocumentDocumentIDFieldinvitecancelParams() *PutDocumentDocumentIDFieldinvitecancelParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PutDocumentDocumentIDFieldinvitecancelParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPutDocumentDocumentIDFieldinvitecancelParamsWithTimeout creates a new PutDocumentDocumentIDFieldinvitecancelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutDocumentDocumentIDFieldinvitecancelParamsWithTimeout(timeout time.Duration) *PutDocumentDocumentIDFieldinvitecancelParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PutDocumentDocumentIDFieldinvitecancelParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewPutDocumentDocumentIDFieldinvitecancelParamsWithContext creates a new PutDocumentDocumentIDFieldinvitecancelParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutDocumentDocumentIDFieldinvitecancelParamsWithContext(ctx context.Context) *PutDocumentDocumentIDFieldinvitecancelParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PutDocumentDocumentIDFieldinvitecancelParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewPutDocumentDocumentIDFieldinvitecancelParamsWithHTTPClient creates a new PutDocumentDocumentIDFieldinvitecancelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutDocumentDocumentIDFieldinvitecancelParamsWithHTTPClient(client *http.Client) *PutDocumentDocumentIDFieldinvitecancelParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &PutDocumentDocumentIDFieldinvitecancelParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*PutDocumentDocumentIDFieldinvitecancelParams contains all the parameters to send to the API endpoint
for the put document document ID fieldinvitecancel operation typically these are written to a http.Request
*/
type PutDocumentDocumentIDFieldinvitecancelParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*DocumentID*/
	DocumentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) WithTimeout(timeout time.Duration) *PutDocumentDocumentIDFieldinvitecancelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) WithContext(ctx context.Context) *PutDocumentDocumentIDFieldinvitecancelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) WithHTTPClient(client *http.Client) *PutDocumentDocumentIDFieldinvitecancelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) WithAuthorization(authorization string) *PutDocumentDocumentIDFieldinvitecancelParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithDocumentID adds the documentID to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) WithDocumentID(documentID string) *PutDocumentDocumentIDFieldinvitecancelParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the put document document ID fieldinvitecancel params
func (o *PutDocumentDocumentIDFieldinvitecancelParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WriteToRequest writes these params to a swagger request
func (o *PutDocumentDocumentIDFieldinvitecancelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param document_id
	if err := r.SetPathParam("document_id", o.DocumentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
