// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetUserDocumentsReader is a Reader for the GetUserDocuments structure.
type GetUserDocumentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserDocumentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserDocumentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUserDocumentsOK creates a GetUserDocumentsOK with default headers values
func NewGetUserDocumentsOK() *GetUserDocumentsOK {
	return &GetUserDocumentsOK{}
}

/*GetUserDocumentsOK handles this case with default header values.

GetUserDocumentsOK get user documents o k
*/
type GetUserDocumentsOK struct {
	Payload interface{}
}

func (o *GetUserDocumentsOK) Error() string {
	return fmt.Sprintf("[GET /user/documents][%d] getUserDocumentsOK  %+v", 200, o.Payload)
}

func (o *GetUserDocumentsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetUserDocumentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
