// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetUserDocumentsv2Reader is a Reader for the GetUserDocumentsv2 structure.
type GetUserDocumentsv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserDocumentsv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserDocumentsv2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUserDocumentsv2OK creates a GetUserDocumentsv2OK with default headers values
func NewGetUserDocumentsv2OK() *GetUserDocumentsv2OK {
	return &GetUserDocumentsv2OK{}
}

/*GetUserDocumentsv2OK handles this case with default header values.

GetUserDocumentsv2OK get user documentsv2 o k
*/
type GetUserDocumentsv2OK struct {
	Payload []*GetUserDocumentsv2OKBodyItems0
}

func (o *GetUserDocumentsv2OK) Error() string {
	return fmt.Sprintf("[GET /user/documentsv2][%d] getUserDocumentsv2OK  %+v", 200, o.Payload)
}

func (o *GetUserDocumentsv2OK) GetPayload() []*GetUserDocumentsv2OKBodyItems0 {
	return o.Payload
}

func (o *GetUserDocumentsv2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetUserDocumentsv2OKBodyItems0 get user documentsv2 o k body items0
swagger:model GetUserDocumentsv2OKBodyItems0
*/
type GetUserDocumentsv2OKBodyItems0 struct {

	//
	Empty string `json:",omitempty"`

	// attachments
	Attachments []interface{} `json:"attachments"`

	// checks
	Checks []interface{} `json:"checks"`

	// created
	Created string `json:"created,omitempty"`

	// document group info
	DocumentGroupInfo *GetUserDocumentsv2OKBodyItems0DocumentGroupInfo `json:"document_group_info,omitempty"`

	// document group template info
	DocumentGroupTemplateInfo []interface{} `json:"document_group_template_info"`

	// document name
	DocumentName string `json:"document_name,omitempty"`

	// enumeration options
	EnumerationOptions []interface{} `json:"enumeration_options"`

	// field invites
	FieldInvites []interface{} `json:"field_invites"`

	// fields
	Fields []*GetUserDocumentsv2OKBodyItems0FieldsItems0 `json:"fields"`

	// hyperlinks
	Hyperlinks []interface{} `json:"hyperlinks"`

	// id
	ID string `json:"id,omitempty"`

	// inserts
	Inserts []interface{} `json:"inserts"`

	// integrations
	Integrations []interface{} `json:"integrations"`

	// notary invites
	NotaryInvites []interface{} `json:"notary_invites"`

	// origin document id
	OriginDocumentID string `json:"origin_document_id,omitempty"`

	// origin user id
	OriginUserID string `json:"origin_user_id,omitempty"`

	// original filename
	OriginalFilename string `json:"original_filename,omitempty"`

	// originator organization settings
	OriginatorOrganizationSettings []*GetUserDocumentsv2OKBodyItems0OriginatorOrganizationSettingsItems0 `json:"originator_organization_settings"`

	// owner
	Owner string `json:"owner,omitempty"`

	// page count
	PageCount string `json:"page_count,omitempty"`

	// radiobuttons
	Radiobuttons []interface{} `json:"radiobuttons"`

	// requests
	Requests []interface{} `json:"requests"`

	// roles
	Roles []*GetUserDocumentsv2OKBodyItems0RolesItems0 `json:"roles"`

	// routing details
	RoutingDetails []*GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0 `json:"routing_details"`

	// seals
	Seals []interface{} `json:"seals"`

	// settings
	Settings *GetUserDocumentsv2OKBodyItems0Settings `json:"settings,omitempty"`

	// signatures
	Signatures []interface{} `json:"signatures"`

	// tags
	Tags []*GetUserDocumentsv2OKBodyItems0TagsItems0 `json:"tags"`

	// template
	Template bool `json:"template,omitempty"`

	// texts
	Texts []interface{} `json:"texts"`

	// thumbnail
	Thumbnail *GetUserDocumentsv2OKBodyItems0Thumbnail `json:"thumbnail,omitempty"`

	// updated
	Updated string `json:"updated,omitempty"`

	// user id
	UserID string `json:"user_id,omitempty"`

	// version time
	VersionTime string `json:"version_time,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0
func (o *GetUserDocumentsv2OKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDocumentGroupInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFields(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateOriginatorOrganizationSettings(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRoles(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRoutingDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSettings(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateThumbnail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0) validateDocumentGroupInfo(formats strfmt.Registry) error {

	if swag.IsZero(o.DocumentGroupInfo) { // not required
		return nil
	}

	if o.DocumentGroupInfo != nil {
		if err := o.DocumentGroupInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("document_group_info")
			}
			return err
		}
	}

	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0) validateFields(formats strfmt.Registry) error {

	if swag.IsZero(o.Fields) { // not required
		return nil
	}

	for i := 0; i < len(o.Fields); i++ {
		if swag.IsZero(o.Fields[i]) { // not required
			continue
		}

		if o.Fields[i] != nil {
			if err := o.Fields[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("fields" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0) validateOriginatorOrganizationSettings(formats strfmt.Registry) error {

	if swag.IsZero(o.OriginatorOrganizationSettings) { // not required
		return nil
	}

	for i := 0; i < len(o.OriginatorOrganizationSettings); i++ {
		if swag.IsZero(o.OriginatorOrganizationSettings[i]) { // not required
			continue
		}

		if o.OriginatorOrganizationSettings[i] != nil {
			if err := o.OriginatorOrganizationSettings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("originator_organization_settings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0) validateRoles(formats strfmt.Registry) error {

	if swag.IsZero(o.Roles) { // not required
		return nil
	}

	for i := 0; i < len(o.Roles); i++ {
		if swag.IsZero(o.Roles[i]) { // not required
			continue
		}

		if o.Roles[i] != nil {
			if err := o.Roles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("roles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0) validateRoutingDetails(formats strfmt.Registry) error {

	if swag.IsZero(o.RoutingDetails) { // not required
		return nil
	}

	for i := 0; i < len(o.RoutingDetails); i++ {
		if swag.IsZero(o.RoutingDetails[i]) { // not required
			continue
		}

		if o.RoutingDetails[i] != nil {
			if err := o.RoutingDetails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("routing_details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0) validateSettings(formats strfmt.Registry) error {

	if swag.IsZero(o.Settings) { // not required
		return nil
	}

	if o.Settings != nil {
		if err := o.Settings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("settings")
			}
			return err
		}
	}

	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0) validateTags(formats strfmt.Registry) error {

	if swag.IsZero(o.Tags) { // not required
		return nil
	}

	for i := 0; i < len(o.Tags); i++ {
		if swag.IsZero(o.Tags[i]) { // not required
			continue
		}

		if o.Tags[i] != nil {
			if err := o.Tags[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tags" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0) validateThumbnail(formats strfmt.Registry) error {

	if swag.IsZero(o.Thumbnail) { // not required
		return nil
	}

	if o.Thumbnail != nil {
		if err := o.Thumbnail.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("thumbnail")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0DocumentGroupInfo get user documentsv2 o k body items0 document group info
swagger:model GetUserDocumentsv2OKBodyItems0DocumentGroupInfo
*/
type GetUserDocumentsv2OKBodyItems0DocumentGroupInfo struct {

	// doc count in group
	DocCountInGroup int64 `json:"doc_count_in_group,omitempty"`

	// document group id
	DocumentGroupID string `json:"document_group_id,omitempty"`

	// document group name
	DocumentGroupName string `json:"document_group_name,omitempty"`

	// invite id
	InviteID string `json:"invite_id,omitempty"`

	// invite status
	InviteStatus string `json:"invite_status,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 document group info
func (o *GetUserDocumentsv2OKBodyItems0DocumentGroupInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0DocumentGroupInfo) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0DocumentGroupInfo) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0DocumentGroupInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0FieldsItems0 get user documentsv2 o k body items0 fields items0
swagger:model GetUserDocumentsv2OKBodyItems0FieldsItems0
*/
type GetUserDocumentsv2OKBodyItems0FieldsItems0 struct {

	// element id
	ElementID string `json:"element_id,omitempty"`

	// field id
	FieldID string `json:"field_id,omitempty"`

	// field request canceled
	FieldRequestCanceled bool `json:"field_request_canceled,omitempty"`

	// field request id
	FieldRequestID string `json:"field_request_id,omitempty"`

	// fulfiller
	Fulfiller string `json:"fulfiller,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// json attributes
	JSONAttributes *GetUserDocumentsv2OKBodyItems0FieldsItems0JSONAttributes `json:"json_attributes,omitempty"`

	// originator
	Originator string `json:"originator,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// role id
	RoleID string `json:"role_id,omitempty"`

	// template field id
	TemplateFieldID string `json:"template_field_id,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 fields items0
func (o *GetUserDocumentsv2OKBodyItems0FieldsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateJSONAttributes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0FieldsItems0) validateJSONAttributes(formats strfmt.Registry) error {

	if swag.IsZero(o.JSONAttributes) { // not required
		return nil
	}

	if o.JSONAttributes != nil {
		if err := o.JSONAttributes.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("json_attributes")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0FieldsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0FieldsItems0) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0FieldsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0FieldsItems0JSONAttributes get user documentsv2 o k body items0 fields items0 JSON attributes
swagger:model GetUserDocumentsv2OKBodyItems0FieldsItems0JSONAttributes
*/
type GetUserDocumentsv2OKBodyItems0FieldsItems0JSONAttributes struct {

	// align
	Align string `json:"align,omitempty"`

	// arrangement
	Arrangement string `json:"arrangement,omitempty"`

	// bold
	Bold bool `json:"bold,omitempty"`

	// font
	Font string `json:"font,omitempty"`

	// height
	Height int64 `json:"height,omitempty"`

	// italic
	Italic bool `json:"italic,omitempty"`

	// max chars
	MaxChars int64 `json:"max_chars,omitempty"`

	// max lines
	MaxLines int64 `json:"max_lines,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// page number
	PageNumber int64 `json:"page_number,omitempty"`

	// required
	Required bool `json:"required,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`

	// underline
	Underline bool `json:"underline,omitempty"`

	// valign
	Valign string `json:"valign,omitempty"`

	// width
	Width int64 `json:"width,omitempty"`

	// x
	X int64 `json:"x,omitempty"`

	// y
	Y int64 `json:"y,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 fields items0 JSON attributes
func (o *GetUserDocumentsv2OKBodyItems0FieldsItems0JSONAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0FieldsItems0JSONAttributes) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0FieldsItems0JSONAttributes) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0FieldsItems0JSONAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0OriginatorOrganizationSettingsItems0 get user documentsv2 o k body items0 originator organization settings items0
swagger:model GetUserDocumentsv2OKBodyItems0OriginatorOrganizationSettingsItems0
*/
type GetUserDocumentsv2OKBodyItems0OriginatorOrganizationSettingsItems0 struct {

	// setting
	Setting string `json:"setting,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 originator organization settings items0
func (o *GetUserDocumentsv2OKBodyItems0OriginatorOrganizationSettingsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0OriginatorOrganizationSettingsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0OriginatorOrganizationSettingsItems0) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0OriginatorOrganizationSettingsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0RolesItems0 get user documentsv2 o k body items0 roles items0
swagger:model GetUserDocumentsv2OKBodyItems0RolesItems0
*/
type GetUserDocumentsv2OKBodyItems0RolesItems0 struct {

	// name
	Name string `json:"name,omitempty"`

	// signing order
	SigningOrder string `json:"signing_order,omitempty"`

	// unique id
	UniqueID string `json:"unique_id,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 roles items0
func (o *GetUserDocumentsv2OKBodyItems0RolesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0RolesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0RolesItems0) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0RolesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0 get user documentsv2 o k body items0 routing details items0
swagger:model GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0
*/
type GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0 struct {

	// cc
	Cc []interface{} `json:"cc"`

	// cc step
	CcStep []interface{} `json:"cc_step"`

	// created
	Created string `json:"created,omitempty"`

	// data
	Data []*GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0DataItems0 `json:"data"`

	// id
	ID string `json:"id,omitempty"`

	// invite link instructions
	InviteLinkInstructions string `json:"invite_link_instructions,omitempty"`

	// updated
	Updated int64 `json:"updated,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 routing details items0
func (o *GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0DataItems0 get user documentsv2 o k body items0 routing details items0 data items0
swagger:model GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0DataItems0
*/
type GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0DataItems0 struct {

	// default email
	DefaultEmail string `json:"default_email,omitempty"`

	// inviter role
	InviterRole bool `json:"inviter_role,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// role id
	RoleID string `json:"role_id,omitempty"`

	// signing order
	SigningOrder int64 `json:"signing_order,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 routing details items0 data items0
func (o *GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0DataItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0DataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0DataItems0) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0RoutingDetailsItems0DataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0Settings get user documentsv2 o k body items0 settings
swagger:model GetUserDocumentsv2OKBodyItems0Settings
*/
type GetUserDocumentsv2OKBodyItems0Settings struct {

	// add signature stamp
	AddSignatureStamp bool `json:"add_signature_stamp,omitempty"`

	// add signature stamp with name
	AddSignatureStampWithName bool `json:"add_signature_stamp_with_name,omitempty"`

	// audit trail completion retention days
	AuditTrailCompletionRetentionDays bool `json:"audit_trail_completion_retention_days,omitempty"`

	// block export options when credit card validation is used
	BlockExportOptionsWhenCreditCardValidationIsUsed bool `json:"block_export_options_when_credit_card_validation_is_used,omitempty"`

	// block login via social networks
	BlockLoginViaSocialNetworks bool `json:"block_login_via_social_networks,omitempty"`

	// cfr title 21 part 11
	CfrTitle21Part11 bool `json:"cfr_title_21_part_11,omitempty"`

	// cloud auto export
	CloudAutoExport bool `json:"cloud_auto_export,omitempty"`

	// cloud export with history
	CloudExportWithHistory bool `json:"cloud_export_with_history,omitempty"`

	// copy export
	CopyExport bool `json:"copy_export,omitempty"`

	// digitally sign dowloaded docs
	DigitallySignDowloadedDocs bool `json:"digitally_sign_dowloaded_docs,omitempty"`

	// disable email notifications
	DisableEmailNotifications bool `json:"disable_email_notifications,omitempty"`

	// document attachment only for signer
	DocumentAttachmentOnlyForSigner bool `json:"document_attachment_only_for_signer,omitempty"`

	// document completion retention days
	DocumentCompletionRetentionDays bool `json:"document_completion_retention_days,omitempty"`

	// document guide
	DocumentGuide bool `json:"document_guide,omitempty"`

	// document schema extended
	DocumentSchemaExtended bool `json:"document_schema_extended,omitempty"`

	// electronic consent required
	ElectronicConsentRequired bool `json:"electronic_consent_required,omitempty"`

	// electronic consent text
	ElectronicConsentText bool `json:"electronic_consent_text,omitempty"`

	// email admin on banned login
	EmailAdminOnBannedLogin bool `json:"email_admin_on_banned_login,omitempty"`

	// emailed docs include history
	EmailedDocsIncludeHistory bool `json:"emailed_docs_include_history,omitempty"`

	// enable advanced threat protection
	EnableAdvancedThreatProtection bool `json:"enable_advanced_threat_protection,omitempty"`

	// enable full story tracker
	EnableFullStoryTracker bool `json:"enable_full_story_tracker,omitempty"`

	// enable hyperlink protection
	EnableHyperlinkProtection bool `json:"enable_hyperlink_protection,omitempty"`

	// front end session length
	FrontEndSessionLength bool `json:"front_end_session_length,omitempty"`

	// invite completion redirect url
	InviteCompletionRedirectURL bool `json:"invite_completion_redirect_url,omitempty"`

	// invite decline redirect url
	InviteDeclineRedirectURL bool `json:"invite_decline_redirect_url,omitempty"`

	// invite update notifications for all invites at invite create
	InviteUpdateNotificationsForAllInvitesAtInviteCreate bool `json:"invite_update_notifications_for_all_invites_at_invite_create,omitempty"`

	// logout on signing
	LogoutOnSigning bool `json:"logout_on_signing,omitempty"`

	// mobileweb option
	MobilewebOption bool `json:"mobileweb_option,omitempty"`

	// no document attachment
	NoDocumentAttachment bool `json:"no_document_attachment,omitempty"`

	// no document file attachments
	NoDocumentFileAttachments bool `json:"no_document_file_attachments,omitempty"`

	// no user signature return
	NoUserSignatureReturn bool `json:"no_user_signature_return,omitempty"`

	// only administrator is able to invite to the team
	OnlyAdministratorIsAbleToInviteToTheTeam bool `json:"only_administrator_is_able_to_invite_to_the_team,omitempty"`

	// org allowed team admins
	OrgAllowedTeamAdmins bool `json:"org_allowed_team_admins,omitempty"`

	// pending invite document view notification
	PendingInviteDocumentViewNotification bool `json:"pending_invite_document_view_notification,omitempty"`

	// require authentication for invites
	RequireAuthenticationForInvites bool `json:"require_authentication_for_invites,omitempty"`

	// require drawn signatures
	RequireDrawnSignatures bool `json:"require_drawn_signatures,omitempty"`

	// require email subject
	RequireEmailSubject bool `json:"require_email_subject,omitempty"`

	// require login for signing
	RequireLoginForSigning bool `json:"require_login_for_signing,omitempty"`

	// required preset signature name
	RequiredPresetSignatureName bool `json:"required_preset_signature_name,omitempty"`

	// restrict download
	RestrictDownload bool `json:"restrict_download,omitempty"`

	// signing link document download
	SigningLinkDocumentDownload bool `json:"signing_link_document_download,omitempty"`

	// sso only login
	SsoOnlyLogin bool `json:"sso-only-login,omitempty"`

	// unsuccessful logout attempts allowed
	UnsuccessfulLogoutAttemptsAllowed bool `json:"unsuccessful_logout_attempts_allowed,omitempty"`

	// upload limit
	UploadLimit bool `json:"upload_limit,omitempty"`

	// watermark downloaded document
	WatermarkDownloadedDocument bool `json:"watermark_downloaded_document,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 settings
func (o *GetUserDocumentsv2OKBodyItems0Settings) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0Settings) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0Settings) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0Settings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0TagsItems0 get user documentsv2 o k body items0 tags items0
swagger:model GetUserDocumentsv2OKBodyItems0TagsItems0
*/
type GetUserDocumentsv2OKBodyItems0TagsItems0 struct {

	// name
	Name string `json:"name,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 tags items0
func (o *GetUserDocumentsv2OKBodyItems0TagsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0TagsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0TagsItems0) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0TagsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetUserDocumentsv2OKBodyItems0Thumbnail get user documentsv2 o k body items0 thumbnail
swagger:model GetUserDocumentsv2OKBodyItems0Thumbnail
*/
type GetUserDocumentsv2OKBodyItems0Thumbnail struct {

	// large
	Large string `json:"large,omitempty"`

	// medium
	Medium string `json:"medium,omitempty"`

	// small
	Small string `json:"small,omitempty"`
}

// Validate validates this get user documentsv2 o k body items0 thumbnail
func (o *GetUserDocumentsv2OKBodyItems0Thumbnail) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0Thumbnail) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserDocumentsv2OKBodyItems0Thumbnail) UnmarshalBinary(b []byte) error {
	var res GetUserDocumentsv2OKBodyItems0Thumbnail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
