// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutUserParams creates a new PutUserParams object
// with the default values initialized.
func NewPutUserParams() *PutUserParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
		contentTypeDefault   = string("application/json")
	)
	return &PutUserParams{
		Authorization: authorizationDefault,
		ContentType:   &contentTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPutUserParamsWithTimeout creates a new PutUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutUserParamsWithTimeout(timeout time.Duration) *PutUserParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
		contentTypeDefault   = string("application/json")
	)
	return &PutUserParams{
		Authorization: authorizationDefault,
		ContentType:   &contentTypeDefault,

		timeout: timeout,
	}
}

// NewPutUserParamsWithContext creates a new PutUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutUserParamsWithContext(ctx context.Context) *PutUserParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
		contentTypeDefault   = string("application/json")
	)
	return &PutUserParams{
		Authorization: authorizationDefault,
		ContentType:   &contentTypeDefault,

		Context: ctx,
	}
}

// NewPutUserParamsWithHTTPClient creates a new PutUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutUserParamsWithHTTPClient(client *http.Client) *PutUserParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
		contentTypeDefault   = string("application/json")
	)
	return &PutUserParams{
		Authorization: authorizationDefault,
		ContentType:   &contentTypeDefault,
		HTTPClient:    client,
	}
}

/*PutUserParams contains all the parameters to send to the API endpoint
for the put user operation typically these are written to a http.Request
*/
type PutUserParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string
	/*ContentType*/
	ContentType *string
	/*Body*/
	Body PutUserBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put user params
func (o *PutUserParams) WithTimeout(timeout time.Duration) *PutUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put user params
func (o *PutUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put user params
func (o *PutUserParams) WithContext(ctx context.Context) *PutUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put user params
func (o *PutUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put user params
func (o *PutUserParams) WithHTTPClient(client *http.Client) *PutUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put user params
func (o *PutUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the put user params
func (o *PutUserParams) WithAuthorization(authorization string) *PutUserParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the put user params
func (o *PutUserParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithContentType adds the contentType to the put user params
func (o *PutUserParams) WithContentType(contentType *string) *PutUserParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the put user params
func (o *PutUserParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithBody adds the body to the put user params
func (o *PutUserParams) WithBody(body PutUserBody) *PutUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put user params
func (o *PutUserParams) SetBody(body PutUserBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PutUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}

	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
