// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostTemplateTemplateIDCopyReader is a Reader for the PostTemplateTemplateIDCopy structure.
type PostTemplateTemplateIDCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTemplateTemplateIDCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostTemplateTemplateIDCopyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostTemplateTemplateIDCopyOK creates a PostTemplateTemplateIDCopyOK with default headers values
func NewPostTemplateTemplateIDCopyOK() *PostTemplateTemplateIDCopyOK {
	return &PostTemplateTemplateIDCopyOK{}
}

/*PostTemplateTemplateIDCopyOK handles this case with default header values.

PostTemplateTemplateIDCopyOK post template template Id copy o k
*/
type PostTemplateTemplateIDCopyOK struct {
	Payload *PostTemplateTemplateIDCopyOKBody
}

func (o *PostTemplateTemplateIDCopyOK) Error() string {
	return fmt.Sprintf("[POST /template/{template_id}/copy][%d] postTemplateTemplateIdCopyOK  %+v", 200, o.Payload)
}

func (o *PostTemplateTemplateIDCopyOK) GetPayload() *PostTemplateTemplateIDCopyOKBody {
	return o.Payload
}

func (o *PostTemplateTemplateIDCopyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostTemplateTemplateIDCopyOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostTemplateTemplateIDCopyBody post template template ID copy body
swagger:model PostTemplateTemplateIDCopyBody
*/
type PostTemplateTemplateIDCopyBody struct {

	// document name
	DocumentName string `json:"document_name,omitempty"`
}

// Validate validates this post template template ID copy body
func (o *PostTemplateTemplateIDCopyBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTemplateTemplateIDCopyBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTemplateTemplateIDCopyBody) UnmarshalBinary(b []byte) error {
	var res PostTemplateTemplateIDCopyBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostTemplateTemplateIDCopyOKBody post template template ID copy o k body
swagger:model PostTemplateTemplateIDCopyOKBody
*/
type PostTemplateTemplateIDCopyOKBody struct {

	// document name
	DocumentName string `json:"document_name,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this post template template ID copy o k body
func (o *PostTemplateTemplateIDCopyOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTemplateTemplateIDCopyOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTemplateTemplateIDCopyOKBody) UnmarshalBinary(b []byte) error {
	var res PostTemplateTemplateIDCopyOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
