// Code generated by go-swagger; DO NOT EDIT.

package smart_fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new smart fields API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for smart fields API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	PostDocumentDocumentIDIntegrationObjectSmartfields(params *PostDocumentDocumentIDIntegrationObjectSmartfieldsParams) (*PostDocumentDocumentIDIntegrationObjectSmartfieldsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  PostDocumentDocumentIDIntegrationObjectSmartfields prefills smart fields

  Prefills smart fields.

You can add Smart Fields to a template though web UI only. <br>
**Note:** names of Smart Fields are case sensetive.
*/
func (a *Client) PostDocumentDocumentIDIntegrationObjectSmartfields(params *PostDocumentDocumentIDIntegrationObjectSmartfieldsParams) (*PostDocumentDocumentIDIntegrationObjectSmartfieldsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostDocumentDocumentIDIntegrationObjectSmartfieldsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostDocumentDocumentIDIntegrationObjectSmartfields",
		Method:             "POST",
		PathPattern:        "/document/{document_id}/integration/object/smartfields",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostDocumentDocumentIDIntegrationObjectSmartfieldsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostDocumentDocumentIDIntegrationObjectSmartfieldsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostDocumentDocumentIDIntegrationObjectSmartfields: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
