// Code generated by go-swagger; DO NOT EDIT.

package o_auth2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOauth2TokenParams creates a new GetOauth2TokenParams object
// with the default values initialized.
func NewGetOauth2TokenParams() *GetOauth2TokenParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetOauth2TokenParams{
		Authorization: authorizationDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOauth2TokenParamsWithTimeout creates a new GetOauth2TokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOauth2TokenParamsWithTimeout(timeout time.Duration) *GetOauth2TokenParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetOauth2TokenParams{
		Authorization: authorizationDefault,

		timeout: timeout,
	}
}

// NewGetOauth2TokenParamsWithContext creates a new GetOauth2TokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOauth2TokenParamsWithContext(ctx context.Context) *GetOauth2TokenParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetOauth2TokenParams{
		Authorization: authorizationDefault,

		Context: ctx,
	}
}

// NewGetOauth2TokenParamsWithHTTPClient creates a new GetOauth2TokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOauth2TokenParamsWithHTTPClient(client *http.Client) *GetOauth2TokenParams {
	var (
		authorizationDefault = string("Bearer {{access_token}}")
	)
	return &GetOauth2TokenParams{
		Authorization: authorizationDefault,
		HTTPClient:    client,
	}
}

/*GetOauth2TokenParams contains all the parameters to send to the API endpoint
for the get oauth2 token operation typically these are written to a http.Request
*/
type GetOauth2TokenParams struct {

	/*Authorization
	  Bearer followed by access_token

	*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get oauth2 token params
func (o *GetOauth2TokenParams) WithTimeout(timeout time.Duration) *GetOauth2TokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get oauth2 token params
func (o *GetOauth2TokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get oauth2 token params
func (o *GetOauth2TokenParams) WithContext(ctx context.Context) *GetOauth2TokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get oauth2 token params
func (o *GetOauth2TokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get oauth2 token params
func (o *GetOauth2TokenParams) WithHTTPClient(client *http.Client) *GetOauth2TokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get oauth2 token params
func (o *GetOauth2TokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get oauth2 token params
func (o *GetOauth2TokenParams) WithAuthorization(authorization string) *GetOauth2TokenParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get oauth2 token params
func (o *GetOauth2TokenParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *GetOauth2TokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
