// Code generated by go-swagger; DO NOT EDIT.

package o_auth2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetOauth2TokenReader is a Reader for the GetOauth2Token structure.
type GetOauth2TokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOauth2TokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOauth2TokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOauth2TokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOauth2TokenOK creates a GetOauth2TokenOK with default headers values
func NewGetOauth2TokenOK() *GetOauth2TokenOK {
	return &GetOauth2TokenOK{}
}

/*GetOauth2TokenOK handles this case with default header values.

Returns the access_token itself as well as its' scope, expiration date, and type.
*/
type GetOauth2TokenOK struct {
	Payload *GetOauth2TokenOKBody
}

func (o *GetOauth2TokenOK) Error() string {
	return fmt.Sprintf("[GET /oauth2/token][%d] getOauth2TokenOK  %+v", 200, o.Payload)
}

func (o *GetOauth2TokenOK) GetPayload() *GetOauth2TokenOKBody {
	return o.Payload
}

func (o *GetOauth2TokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetOauth2TokenOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOauth2TokenBadRequest creates a GetOauth2TokenBadRequest with default headers values
func NewGetOauth2TokenBadRequest() *GetOauth2TokenBadRequest {
	return &GetOauth2TokenBadRequest{}
}

/*GetOauth2TokenBadRequest handles this case with default header values.

"invalid_token" - either incorrect or expired token provided
*/
type GetOauth2TokenBadRequest struct {
}

func (o *GetOauth2TokenBadRequest) Error() string {
	return fmt.Sprintf("[GET /oauth2/token][%d] getOauth2TokenBadRequest ", 400)
}

func (o *GetOauth2TokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetOauth2TokenOKBody get oauth2 token o k body
swagger:model GetOauth2TokenOKBody
*/
type GetOauth2TokenOKBody struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// expires in
	ExpiresIn string `json:"expires_in,omitempty"`

	// scope
	Scope string `json:"scope,omitempty"`

	// token type
	TokenType string `json:"token_type,omitempty"`
}

// Validate validates this get oauth2 token o k body
func (o *GetOauth2TokenOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetOauth2TokenOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOauth2TokenOKBody) UnmarshalBinary(b []byte) error {
	var res GetOauth2TokenOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
